//>>built
define("dojox/mobile/common","dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/lang dojo/_base/window dojo/_base/kernel dojo/dom-class dojo/dom-construct dojo/domReady dojo/ready dojo/touch dijit/registry ./sniff ./uacss".split(" "),function(n,h,k,m,b,r,l,p,s,t,v,u,d){var a=m.getObject("dojox.mobile",!0);b.doc.dojoClick=!0;d("touch")&&(d.add("clicks-prevented",!(4.1<=d("android")||10<=d("ie"))),d("clicks-prevented")&&(a._sendClick=function(a,c){for(var f=a;f;f=f.parentNode)if(f.dojoClick)return;
f=b.doc.createEvent("MouseEvents");f.initMouseEvent("click",!0,!0,b.global,1,c.screenX,c.screenY,c.clientX,c.clientY);a.dispatchEvent(f)}));a.getScreenSize=function(){return{h:b.global.innerHeight||b.doc.documentElement.clientHeight,w:b.global.innerWidth||b.doc.documentElement.clientWidth}};a.updateOrient=function(){var e=a.getScreenSize();l.replace(b.doc.documentElement,e.h>e.w?"dj_portrait":"dj_landscape",e.h>e.w?"dj_landscape":"dj_portrait")};a.updateOrient();a.tabletSize=500;a.detectScreenSize=
function(e){var c=a.getScreenSize(),f=Math.min(c.w,c.h),d,g;if(f>=a.tabletSize&&(e||!this._sz||this._sz<a.tabletSize))d="phone",g="tablet";else if(f<a.tabletSize&&(e||!this._sz||this._sz>=a.tabletSize))d="tablet",g="phone";g&&(l.replace(b.doc.documentElement,"dj_"+g,"dj_"+d),k.publish("/dojox/mobile/screenSize/"+g,[c]));this._sz=f};a.detectScreenSize();a.hideAddressBarWait="number"===typeof h.mblHideAddressBarWait?h.mblHideAddressBarWait:1500;a.hide_1=function(){scrollTo(0,1);a._hidingTimer=0==a._hidingTimer?
200:2*a._hidingTimer;setTimeout(function(){a.isAddressBarHidden()||a._hidingTimer>a.hideAddressBarWait?(a.resizeAll(),a._hiding=!1):setTimeout(a.hide_1,a._hidingTimer)},50)};a.hideAddressBar=function(e){!a.disableHideAddressBar&&!a._hiding&&(a._hiding=!0,a._hidingTimer=d("ios")?200:0,e=screen.availHeight,d("android")&&(e=outerHeight/devicePixelRatio,0==e&&(a._hiding=!1,setTimeout(function(){a.hideAddressBar()},200)),e<=innerHeight&&(e=outerHeight),3>d("android")&&(b.doc.documentElement.style.overflow=
b.body().style.overflow="visible")),b.body().offsetHeight<e&&(b.body().style.minHeight=e+"px",a._resetMinHeight=!0),setTimeout(a.hide_1,a._hidingTimer))};a.isAddressBarHidden=function(){return 1===pageYOffset};a.resizeAll=function(e,c){if(!a.disableResizeAll){k.publish("/dojox/mobile/resizeAll",[e,c]);k.publish("/dojox/mobile/beforeResizeAll",[e,c]);a._resetMinHeight&&(b.body().style.minHeight=a.getScreenSize().h+"px");a.updateOrient();a.detectScreenSize();var f=function(a){var b=a.getParent&&a.getParent();
return!(b&&b.resize||!a.resize)},d=function(a){n.forEach(a.getChildren(),function(a){f(a)&&a.resize();d(a)})};c?(c.resize&&c.resize(),d(c)):n.forEach(n.filter(u.toArray(),f),function(a){a.resize()});k.publish("/dojox/mobile/afterResizeAll",[e,c])}};a.openWindow=function(a,c){b.global.open(a,c||"_blank")};a._detectWindowsTheme=function(){navigator.userAgent.match(/IEMobile\/10\.0/)&&p.create("style",{innerHTML:"@-ms-viewport {width: auto !important}"},b.doc.head);var a=function(){l.add(b.doc.documentElement,
"windows_theme");r.experimental("Dojo Mobile Windows theme","Behavior and appearance of the Windows theme are experimental.")},c=d("windows-theme");if(void 0!==c)c&&a();else{for(var f,h=function(b){return b&&-1!==b.indexOf("/windows/")?(d.add("windows-theme",!0),a(),!0):!1},g=b.doc.styleSheets,c=0;c<g.length;c++)if(!g[c].href){var k=g[c].cssRules||g[c].imports;if(k)for(f=0;f<k.length;f++)if(h(k[f].href))return}f=b.doc.getElementsByTagName("link");for(c=0;c<f.length&&!h(f[c].href);c++);}};!1!==h.mblApplyPageStyles&&
l.add(b.doc.documentElement,"mobile");d("chrome")&&l.add(b.doc.documentElement,"dj_chrome");if(b.global._no_dojo_dm){m=b.global._no_dojo_dm;for(var q in m)a[q]=m[q];a.deviceTheme.setDm(a)}d.add("mblAndroidWorkaround",!1!==h.mblAndroidWorkaround&&3>d("android"),void 0,!0);d.add("mblAndroid3Workaround",!1!==h.mblAndroid3Workaround&&3<=d("android"),void 0,!0);a._detectWindowsTheme();s(function(){l.add(b.body(),"mblBackground")});t(function(){a.detectScreenSize(!0);!1!==h.mblAndroidWorkaroundButtonStyle&&
d("android")&&p.create("style",{innerHTML:"BUTTON,INPUT[type\x3d'button'],INPUT[type\x3d'submit'],INPUT[type\x3d'reset'],INPUT[type\x3d'file']::-webkit-file-upload-button{-webkit-appearance:none;} audio::-webkit-media-controls-play-button,video::-webkit-media-controls-play-button{-webkit-appearance:media-play-button;} video::-webkit-media-controls-fullscreen-button{-webkit-appearance:media-fullscreen-button;}"},b.doc.head,"first");d("mblAndroidWorkaround")&&p.create("style",{innerHTML:".mblView.mblAndroidWorkaround{position:absolute;top:-9999px !important;left:-9999px !important;}"},
b.doc.head,"last");var e=a.resizeAll,c=-1!=navigator.appVersion.indexOf("Mobile")&&!(7<=d("ios"));if(!1!==h.mblHideAddressBar&&c||!0===h.mblForceHideAddressBar)a.hideAddressBar(),!0===h.mblAlwaysHideAddressBar&&(e=a.hideAddressBar);var f=6<=d("ios");if((d("android")||f)&&void 0!==b.global.onorientationchange){var l=e,g,m,n;f?(m=b.doc.documentElement.clientWidth,n=b.doc.documentElement.clientHeight):(e=function(a){var b=k.connect(null,"onresize",null,function(a){k.disconnect(b);l(a)})},g=a.getScreenSize());
k.connect(null,"onresize",null,function(c){if(f){var d=b.doc.documentElement.clientWidth,e=b.doc.documentElement.clientHeight;d==m&&e!=n&&l(c);m=d;n=e}else d=a.getScreenSize(),d.w==g.w&&100<=Math.abs(d.h-g.h)&&l(c),g=d})}k.connect(null,void 0!==b.global.onorientationchange?"onorientationchange":"onresize",null,e);b.body().style.visibility="visible"});return a});
//@ sourceMappingURL=common.js.map